config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'recipes#index'

  resources :recipes, except: [:edit, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy]
  end
  resources :foods, except: [:edit, :update]

  get '/general_shopping_list', to: 'foods#general'
  get '/public_recipes', to: 'recipes#public'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true, length: { minimum: 3 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  def public?
    public
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods
  end

  def new
    @food = Food.new
  end

  def create
    food = current_user.foods.new(food_params)

    if food.save
      redirect_to foods_path, notice: 'New Food was successfully added.'
    else
      flash[:alert] = 'New Food adding Failed. Please try again.'
    end
  end

  def destroy
    food = Food.find(params[:id])

    unless food.user == current_user
      flash[:alert] =
        'You do not have access to delete the Food belongs to other Users.'
    end

    if food.destroy
      flash[:notice] = 'Food was successfully deleted.'
    else
      flash[:alert] = 'Food deleting Failed. Please try again.'
    end
    redirect_back(fallback_location: root_path)
  end

  def general
    @foods = current_user.foods
    current_user.recipes.map do |recipe|
      recipe.recipe_foods.includes(:food).map do |recipe_food|
        food = recipe_food.food
        test = @foods.select { |f| f.name == food.name }[0]
        test.quantity = test.quantity - recipe_food.quantity
      end
    end
    @foods = @foods.select { |f| f.quantity.negative? }
    @foods.each { |f| f.quantity *= -1 }
    @total = 0
    @foods.each do |food|
      @total += (food.price * food.quantity)
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :quantity, :measurement_unit, :price)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    recipe = Recipe.find(params[:recipe_id])
    unless recipe.user == current_user
      flash[:alert] =
        'You do not have access to add an ingredient on a recipe that belongs to other Users.'
      return redirect_to recipes_path
    end

    @recipe_food = RecipeFood.new
    @foods = current_user.foods
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    recipe_food = RecipeFood.new(recipe_food_params)
    recipe_food.recipe = @recipe

    if recipe_food.save
      redirect_to recipe_path(@recipe), notice: 'New ingredient was successfully added.'
    else
      flash[:alert] = 'New Ingredient adding Failed. Please try again.'
    end
  end

  def destroy
    recipe_food = RecipeFood.find(params[:id])

    unless recipe_food.recipe.user == current_user
      flash[:alert] =
        'You do not have access to delete the ingredient belongs to other Users.'
      return redirect_to recipes_path
    end

    if recipe_food.destroy
      flash[:notice] = 'Ingredient was successfully removed.'
    else
      flash[:alert] = 'Ingredient removal Failed. Please try again.'
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = current_user.recipes
  end

  def show
    recipe_test = Recipe.find(params[:id])
    unless recipe_test.user == current_user || recipe_test.public?
      flash[:alert] =
        'You do not have access to see details.'
      return redirect_to recipes_path
    end

    @recipe = Recipe.find(params[:id])
    @recipe_foods = RecipeFood.where(recipe_id: @recipe.id).includes(:food, :recipe)
  end

  def create
    recipe = current_user.recipes.new(recipe_params)

    if recipe.save
      redirect_to recipes_path, notice: 'New recipe was successfully added.'
    else
      flash[:alert] = 'New Recipe adding Failed. Please try again.'
    end
  end

  def new
    @recipe = Recipe.new
  end

  def destroy
    recipe = Recipe.find(params[:id])

    unless recipe.user == current_user
      return flash[:alert] =
               'You do not have access to delete the Recipe belongs to other Users.'
    end

    if recipe.destroy
      flash[:notice] = 'Recipe was successfully deleted.'
    else
      flash[:alert] = 'Recipe deleting Failed. Please try again.'
    end
    redirect_back(fallback_location: root_path)
  end

  def public
    @totals = {}

    @public_recipes = Recipe.where(public: true).includes(:foods, :user).order('created_at DESC')
    @public_recipes.each do |pub|
      total = 0
      RecipeFood.where(recipe_id: pub.id).each do |rec_food|
        total += rec_food.quantity * rec_food.food.price
      end
      @totals[pub.id] = total
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/turbo_controller.rb
class TurboController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      raise e if get?

      if has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/general.html.erb
<div class="flex justify-center text-center p-8">
  <div class="w-[80%]">
    <p class="font-bold text-xl">Shopping List</p>
    <div class="flex flex-wrap justify-around my-4">
      <div><span>Amount of food items to buy: </span><span class="font-bold">&nbsp;<%= @foods.length %></span></div>
      <div><span>Total value of food needed:</span><span class="font-bold">&nbsp;$<%= @total %></span></div>
    </div>
    <table class="w-full text-lg table-auto border-collapse">
      <thead>
        <tr>
          <th class="border border-slate-800 py-2">Food</th>
          <th class="border border-slate-800">Quantity</th>
          <th class="border border-slate-800">Price</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr class="odd:bg-white even:bg-green-100">
            <td class="border border-slate-300 py-2"><%= food.name %></td>
            <td class="border border-slate-300"><%= food.quantity %></td>
            <td class="border border-slate-300">$<%= food.price * food.quantity %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/foods/index.html.erb
<div class="flex justify-center text-center p-8">
  <div class="w-[80%]">
    <div class="text-right mb-8"><%= link_to "Add Food", new_food_path, class: "py-2 px-4 rounded-lg bg-green-300 hover:bg-green-200 hover:shadow-xl" %></div>
    <table class="w-full text-lg table-auto border-collapse">
      <thead>
        <tr>
          <th class="border border-slate-800 py-2">Food</th>
          <th class="border border-slate-800">Quantity</th>
          <th class="border border-slate-800 w-44">Measurement Unit</th>
          <th class="border border-slate-800">Unit Price</th>
          <th class="border border-slate-800">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr class="odd:bg-white even:bg-green-100">
            <td class="border border-slate-300 py-2"><%= food.name %></td>
            <td class="border border-slate-300"><%= food.quantity %></td>
            <td class="border border-slate-300"><%= food.measurement_unit %></td>
            <td class="border border-slate-300">$<%= food.price %></td>
            <td class="border border-slate-300"><%= button_to "Delete", food_path(food.id), method: :delete, class: "bg-red-300 px-2 py-0 my-2 rounded-lg hover:bg-red-500 hover:text-white" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/foods/new.html.erb
<div class="flex justify-center">
  <%= form_with model: @food, class: "mt-16 px-8 py-4 w-96 bg-white rounded-lg shadow-lg h-fit" do |form| %>
    <% if @food.errors.any? %>
      <div>
        <h3><%= pluralize(@food.errors.count, "error") %>occurred: </h3>
        <ul>
          <%= @food.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <h2 class="text-xl font-bold text-center text-gray-700">Add a New Food</h2>
    <div class="my-4">
      <%= form.label :name, "Name" %>
      <%= form.text_field :name, placeholder: "Name", required: true, autofocus: true, class: "px-4 py-2 rounded-md mt-2 w-full bg-blue-100" %>
    </div>
    <div class="my-4">
      <%= form.label :quantity, "Quantity" %>
      <%= form.number_field :quantity, placeholder: 0, required: true, autofocus: true, class: "px-4 py-2 rounded-md mt-2 w-full bg-blue-100" %>
    </div>
    <div class="my-4">
      <%= form.label :measurement_unit, "Measurement Unit" %>
      <%= form.text_field :measurement_unit, placeholder: "kg", required: true, autofocus: true, class: "px-4 py-2 rounded-md mt-2 w-full bg-blue-100" %>
    </div>
    <div class="my-4">
      <%= form.label :price, "Price" %>
      <%= form.number_field :price, placeholder: 100, required: true, autofocus: true, class: "px-4 py-2 rounded-md mt-2 w-full bg-blue-100" %>
    </div>
    <div class="bg-green-300 hover:bg-green-100 rounded-lg py-2 text-center font-bold cursor-pointer mt-8 text-gray-700">
      <%= form.submit "Add Food", data: { disable_with: "Loading" } %>
    </div>
  <% end %>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
  <p class="bg-green-300 py-2 flex justify-center text-gray-800"><%= notice %></p>
<% elsif alert %>
  <p class="bg-red-200 py-2 flex justify-center text-gray-700"><%= alert %></p>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="bg-blue-300 flex justify-around items-center py-4">
  <h1 class="font-bold text-lg text-black bg-white px-2 py-1 border-2 border-black shadow-lg">Shopping on Rails</h1>
  <% if current_user %>
    <%= link_to "Recipes", recipes_path, class: "text-blue-800 underline text-lg hover:text-green-100" %>
    <%= link_to "Foods", foods_path, class: "text-blue-800 underline text-lg hover:text-green-100" %>
    <%= link_to "General Shopping List", "/general_shopping_list", class: "text-blue-800 underline text-lg hover:text-green-100" %>
  <% end %>
  <%= link_to "Public Recipes", "/public_recipes", class: "text-blue-800 underline text-lg hover:text-green-100" %>
  <div>
    <% if current_user %>
      <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "bg-green-300 rounded-md px-2 py-1 hover:bg-green-50"%>
    <% else %>
      <% if current_page?(new_user_session_path) %>
        <%= link_to "Sign up", new_user_registration_path, class: "bg-green-300 rounded-md px-2 py-1 hover:bg-green-50" %>
      <% elsif current_page?(new_user_registration_path) %>
        <%= link_to "Sign in", new_user_session_path, class: "bg-green-300 rounded-md px-2 py-1 hover:bg-green-50" %>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://cdn.tailwindcss.com"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="h-screen bg-gray-200">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/recipe_foods/new.html.erb
<div class="flex justify-center">
  <%= form_with url: recipe_recipe_foods_path, scope: :recipe_food, class: "bg-white rounded-lg p-4 my-16 w-96" do |form| %>
    <p class="text-lg font-bold text-center mb-4">Add Ingredient</p>
    <div class="my-4 flex justify-between">
      <%= form.label :quantity, "Quantity", placeholder: 0 %>
      <%= form.number_field :quantity, class: "bg-blue-100 p-2 rounded-md" %>
    </div>
    <div class="my-4 flex justify-between">
      <%= form.label :food_id, "Food" %>
      <div class="bg-gray-200 p-2 rounded-md">
        <%= form.collection_select(:food_id, @foods, :id, :name) %>
      </div>
    </div>
    <div class="text-center bg-green-300 hover:bg-green-100 py-2 rounded-lg hover:shadow-lg">
      <%= form.submit "Add Ingredient" %>
    </div>
  <% end %>
</div>

app/views/recipes/index.html.erb
<div class="flex justify-center text-center p-8">
  <div class="w-[80%]">
    <div class="text-right mb-8">
      <%= link_to "Add Recipe", new_recipe_path, class: "py-2 px-4 rounded-lg bg-green-300 hover:bg-green-200 hover:shadow-xl" %>
    </div>
    <ul class="flex flex-col items-center py-4">
      <% @recipes.each do |recipe| %>
        <li class="bg-white rounded-lg flex justify-between items-center w-[60%] my-2 py-2 px-4 border-2 border-gray-400 hover:shadow-xl">
          <div class="p-2">
            <div class="mb-2 text-blue-600 hover:text-blue-300 text-xl font-bold">
              <%= link_to recipe.name, recipe_path(recipe) %>
            </div>
            <%= button_to "Remove", recipe_path(recipe.id), method: :delete, class: "bg-red-200 px-2 py-1 rounded-lg hover:bg-red-400 hover:text-white" %>
          </div>
          <div class="w-[80%] px-2 py-1">
            <%= truncate(recipe.description, length: 100) %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="flex justify-center">
  <%= form_with model: @recipe, class: "my-16 px-8 py-4 w-96 bg-white rounded-lg shadow-lg h-fit" do |form| %>
    <% if @recipe.errors.any? %>
      <div>
        <h3><%= pluralize(@recipe.errors.count, "error") %> occurred: </h3>
        <ul>
          <%= @recipe.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <h2 class="text-xl font-bold text-center text-gray-700">Add a New Recipe</h2>
    <div class="my-4">
      <%= form.label :name, "Name" %>
      <%= form.text_field :name, placeholder: "Name", required: true, autofocus: true, class: "px-4 py-2 rounded-md mt-2 w-full bg-blue-100" %>
    </div>
    <div class="my-4">
      <%= form.label :preparation_time, "Preparation Time" %>
      <%= form.number_field :preparation_time, placeholder: 0, required: true, autofocus: true, class: "px-4 py-2 rounded-md mt-2 w-full bg-blue-100" %>
    </div>
    <div class="my-4">
      <%= form.label :cooking_time, "Cooking Time" %>
      <%= form.number_field :cooking_time, placeholder: 0, required: true, autofocus: true, class: "px-4 py-2 rounded-md mt-2 w-full bg-blue-100" %>
    </div>
    <div class="my-4">
      <%= form.label :description, "Description" %>
      <%= form.text_area :description, placeholder: "A description about the recipe", rows: 5, required: true, autofocus: true, class: "px-4 py-2 rounded-md mt-2 w-full bg-blue-100" %>
    </div>
    <div class="my-4">
      <%= form.label :public %><br/>
      <%= form.label :public, "Yes", value: "true" %>
      <%= form.radio_button :public, true, checked: true %> &nbsp; &nbsp;
      <%= form.label :public, "No", value: "false" %>
      <%= form.radio_button :public, false %>
    </div>
    <div class="bg-green-300 hover:bg-green-100 rounded-lg py-2 text-center font-bold cursor-pointer mt-4 text-gray-700">
      <%= form.submit "Add Recipe", data: { disable_with: "Loading" } %>
    </div>
  <% end %>
</div>

app/views/recipes/public.html.erb
<div class="flex justify-center text-center p-8">
  <div class="w-[80%]">
    <p class="text-xl font-bold mb-2">Public Recipes</p>
    <ul class="flex flex-col items-center py-4">
      <% @public_recipes.each do |recipe| %>
        <li class="bg-white rounded-lg flex justify-between items-center w-[60%] my-2 py-2 px-4 border-2 border-gray-400 hover:shadow-xl">
          <div class="p-2">
            <div class="mb-2 text-blue-600 hover:text-blue-300 text-xl font-bold">
              <%= link_to recipe.name, recipe_path(recipe) %>
            </div>
            By: <span class="font-bold"><%= recipe.user.name %></span>
          </div>
          <div class="w-[80%] px-2 py-1 flex flex-col items-center gap-2">
            <div class="flex justify-between w-[50%]">
              <span>Total food items: </span>
              <span class="font-bold"><%= recipe.foods.length %></span>
            </div>
            <div class="flex justify-between w-[50%]">
              <span>Total price:</span>
              <span class="font-bold">$<%= @totals[recipe.id] %></span>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="flex justify-center">
  <div class="my-8 p-8 rounded-lg text-center bg-white w-[50%]">
    <p class="font-bold text-xl"><%= @recipe.name %></p>
    <div class="flex justify-between items-center w-full">
      <div class="mb-2 mt-4 w-48 flex justify-between">
        <p>Preparation Time:</p>
        <p><%= @recipe.preparation_time %> hours</p>
      </div>
      <div>
        Public: &nbsp; &nbsp; <%= t(@recipe.public) %>
      </div>
    </div>
    <div class="my-2 w-48 flex justify-between">
      <p>Cooking Time:</p>
      <p><%= @recipe.cooking_time %> hours</p>
    </div>
    <p class="my-4 text-lg"><%= @recipe.description %></p>
    <div class="flex justify-between w-full">
      <% if @recipe.user == current_user %>
        <div class="border-gray-400 rounded-lg border-2 hover:shadow-xl px-4 py-2 bg-green-300 hover:bg-green-100">
          <%= link_to "Generate Shopping List", general_shopping_list_path %>
        </div>
      <% end %>
      <% if @recipe.user == current_user %>
        <div class="border-gray-400 rounded-lg border-2 hover:shadow-xl px-4 py-2 bg-green-300 hover:bg-green-100">
          <%= link_to "Add Ingredient", new_recipe_recipe_food_path(@recipe) %>
        </div>
      <% end %>
    </div>
    <div class="my-4 text-black border-t-2 border-black"></div>
    <% if @recipe_foods.length > 0 %>
      <table class="w-full table-auto border-collapse">
        <thead>
          <tr>
            <th class="border border-slate-800 py-2">Food</th>
            <th class="border border-slate-800 py-2">Quantity</th>
            <th class="border border-slate-800 py-2">Value</th>
            <th class="border border-slate-800 py-2">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @recipe_foods.each do |recipe_food| %>
            <tr class="odd:bg-white even:bg-green-100">
              <td class="border border-slate-300 py-2"><%= recipe_food.food.name %></td>
              <td class="border border-slate-300 py-2"><%= recipe_food.quantity %></td>
              <td class="border border-slate-300 py-2">$<%= recipe_food.quantity * recipe_food.food.price %></td>
              <td class="border border-slate-300 py-2">
                <% if current_user == recipe_food.recipe.user %>
                  <%= button_to 'Remove', recipe_recipe_food_path(@recipe, recipe_food), method: :delete, class: "bg-red-300 px-2 py-1 rounded-lg hover:bg-red-500 hover:text-white" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <div>Add some new Ingredient.</div>
    <% end %>
  </div>
</div>